version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_development
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
