default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: password
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test
